/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブログ記事の一覧を取得する。
         * @description ブログ記事の一覧を取得する。
         */
        get: operations["api_articles_get_collection"];
        put?: never;
        /**
         * ブログ記事を新規作成する。
         * @description ブログ記事を新規作成する。
         */
        post: operations["api_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定したブログ記事の詳細を取得する。
         * @description 指定したブログ記事の詳細を取得する。
         */
        get: operations["api_articles_id_get"];
        put?: never;
        post?: never;
        /**
         * 指定したブログ記事を削除する。
         * @description 指定したブログ記事を削除する。
         */
        delete: operations["api_articles_id_delete"];
        options?: never;
        head?: never;
        /**
         * 指定したブログ記事を更新する。
         * @description 指定したブログ記事を更新する。
         */
        patch: operations["api_articles_id_patch"];
        trace?: never;
    };
    "/api/articles/{id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 指定したブログ記事を公開済みにする。
         * @description 指定したブログ記事を公開済みにする。
         */
        put: operations["api_articles_idpublication_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{articleId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定したブログ記事に対するコメントの一覧を取得する。
         * @description 指定したブログ記事に対するコメントの一覧を取得する。
         */
        get: operations["api_articles_articleIdcomments_get_collection"];
        put?: never;
        /**
         * 指定したブログ記事に対するコメントを新規作成する。
         * @description 指定したブログ記事に対するコメントを新規作成する。
         */
        post: operations["api_articles_articleIdcomments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定したコメントの詳細を取得する。
         * @description 指定したコメントの詳細を取得する。
         */
        get: operations["api_comments_id_get"];
        put?: never;
        post?: never;
        /**
         * 指定したコメントを削除する。
         * @description 指定したコメントを削除する。
         */
        delete: operations["api_comments_id_delete"];
        options?: never;
        head?: never;
        /**
         * 指定したコメントを更新する。
         * @description 指定したコメントを更新する。
         */
        patch: operations["api_comments_id_patch"];
        trace?: never;
    };
    "/api/media_objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a MediaObject resource.
         * @description Creates a MediaObject resource.
         */
        post: operations["api_media_objects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media_objects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a MediaObject resource.
         * @description Retrieves a MediaObject resource.
         */
        get: operations["api_media_objects_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 使用可能なタグの一覧を取得する。
         * @description 使用可能なタグの一覧を取得する。
         */
        get: operations["api_tags_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ログイン中のユーザー自身の詳細を取得する。
         * @description ログイン中のユーザー自身の詳細を取得する。
         */
        get: operations["api_usersme_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Article-article.write": {
            title: string;
            content?: string | null;
            /**
             * @description #required-on-read
             * @default false
             */
            published?: boolean;
            tags?: ("tag1" | "tag2" | "tag3" | "tag4" | "tag5" | "tag6" | "tag7" | "tag8" | "tag9" | "tag10")[];
            relatedArticles?: components["schemas"]["Article-article.write"][];
            /**
             * Format: date
             * @example 2026-01-01
             */
            date: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            image?: string | null;
        };
        "Article-article.write.jsonMergePatch": {
            title?: string;
            content?: string | null;
            /**
             * @description #required-on-read
             * @default false
             */
            published?: boolean;
            tags?: ("tag1" | "tag2" | "tag3" | "tag4" | "tag5" | "tag6" | "tag7" | "tag8" | "tag9" | "tag10")[];
            relatedArticles?: components["schemas"]["Article-article.write"][];
            /**
             * Format: date
             * @example 2026-01-01
             */
            date?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            image?: string | null;
        };
        "Article.jsonld-article.read.item": {
            relatedArticles?: components["schemas"]["Article.jsonld-article.read.item"][];
            /**
             * Format: date
             * @example 2026-01-01
             */
            date?: string;
            image?: components["schemas"]["MediaObject.jsonld-article.read.item"] | null;
            createdBy?: string;
            updatedBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            readonly popular?: boolean;
        } & (components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            title: string;
            content?: string | null;
            /** @default false */
            published: boolean;
            comments?: components["schemas"]["Comment.jsonld-article.read.item"][];
            tags?: ("tag1" | "tag2" | "tag3" | "tag4" | "tag5" | "tag6" | "tag7" | "tag8" | "tag9" | "tag10")[];
        });
        "Article.jsonld-article.read.list": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            title: string;
            content?: string | null;
            /**
             * @description #required-on-read
             * @default false
             */
            published?: boolean;
            tags?: ("tag1" | "tag2" | "tag3" | "tag4" | "tag5" | "tag6" | "tag7" | "tag8" | "tag9" | "tag10")[];
            /**
             * Format: date
             * @example 2026-01-01
             */
            date: string;
            readonly popular: boolean;
        };
        "Comment-comment.write": {
            content: string;
        };
        "Comment-comment.write_comment.write.patch.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @description #required-on-read
             * @example https://example.com/
             */
            article?: string;
            content?: string;
        };
        "Comment.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            article: string;
            content: string;
            createdBy?: string;
            updatedBy?: string;
        };
        "Comment.jsonld-article.read.item": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            content: string;
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status?: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: unknown[];
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status?: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: unknown[];
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status?: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status?: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        "MediaObject.jsonld-article.read.item": components["schemas"]["HydraItemBaseSchema"] & {
            readonly contentUrl: string | null;
        };
        "MediaObject.jsonld-media_object.read.item": components["schemas"]["HydraItemBaseSchema"] & {
            readonly contentUrl: string | null;
        };
        "Tag.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: number;
            label?: string;
        };
        "User.jsonld-user.read.item": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            clerkUserId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_articles_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                title?: string;
                "comments.content"?: string;
                "date[before]"?: string;
                "date[strictly_before]"?: string;
                "date[after]"?: string;
                "date[strictly_after]"?: string;
                published?: boolean;
                id?: number;
                "id[]"?: number[];
                "id[between]"?: string;
                "id[gt]"?: string;
                "id[gte]"?: string;
                "id[lt]"?: string;
                "id[lte]"?: string;
                "exists[content]"?: boolean;
                "exists[comments]"?: boolean;
                "order[id]"?: "asc" | "desc";
                "order[date]"?: "asc" | "desc";
                /** @description ブログ記事のタイトルと本文を横断的に部分一致で検索する。 */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Article.jsonld-article.read.list"][];
                    };
                };
            };
        };
    };
    api_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Article resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Article-article.write"];
            };
        };
        responses: {
            /** @description Article resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Article.jsonld-article.read.item"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_articles_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ブログ記事ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Article.jsonld-article.read.item"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_articles_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ブログ記事ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_articles_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ブログ記事ID */
                id: number;
            };
            cookie?: never;
        };
        /** @description The updated Article resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Article-article.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Article resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Article.jsonld-article.read.item"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_articles_idpublication_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ブログ記事ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Article.jsonld-article.read.item"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_articles_articleIdcomments_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
            };
            header?: never;
            path: {
                /** @description ブログ記事ID */
                articleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Comment.jsonld"][];
                    };
                };
            };
        };
    };
    api_articles_articleIdcomments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ブログ記事ID */
                articleId: number;
            };
            cookie?: never;
        };
        /** @description The new Comment resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Comment-comment.write"];
            };
        };
        responses: {
            /** @description Comment resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Comment.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_comments_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description コメントID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Comment.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_comments_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description コメントID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_comments_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description コメントID */
                id: number;
            };
            cookie?: never;
        };
        /** @description The updated Comment resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Comment-comment.write_comment.write.patch.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Comment resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Comment.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_media_objects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new MediaObject resource */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description MediaObject resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["MediaObject.jsonld-media_object.read.item"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_media_objects_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MediaObject identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MediaObject resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["MediaObject.jsonld-media_object.read.item"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_tags_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Tag.jsonld"][];
                    };
                };
            };
        };
    };
    api_usersme_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld-user.read.item"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
